### ISSUE TITLE
Shut down bot instance with command

### ISSUE THREAD

**Issue by miam-miam100** [Diegovano/bomboclaat#26]
Needs to use database to only allow certain people to do it.

**Comment by Diegovano** [comment]
We already have a leave command? 
What else would you want it to do?

**Comment by miam-miam100** [comment]
No actually quits running the bot, so if there are two bots we can shut one down.

**Comment by Diegovano** [comment]
Yes but if you run the leave command, they will both shutdown

**Comment by Diegovano** [comment]
However, in the long run this won't be necessary

**Comment by Diegovano** [comment]
Solution is to use different prefixes to avoid conflicts
