### ISSUE TITLE
When YouTube URL is sent on channel, allow the user to directly add the track to the queue (with reactions)

### ISSUE THREAD

**Issue by miam-miam100** [Diegovano/bomboclaat#27]

**Comment by Diegovano** [comment]
Please explain

**Comment by miam-miam100** [comment]
If someone types a youtube url on the server, the bot should add a reaction which would then add that url to the queue.

**Comment by Diegovano** [comment]
Could be an interesting feature, but I feel we should stick to the philosophy that the bot only answers when it is explicitly called with the prefix
