### ISSUE TITLE
Remove moment (if possible)

### ISSUE THREAD

**Issue by miam-miam100** [Diegovano/bomboclaat#29]
Slowing us down and is only used once

**Comment by Diegovano** [comment]
Moment.js is a legacy project. I just used it because it did the job (converting from ISO 8601 durations (from YouTube algorithm).

They recommend that we use an alternative such as [Luxon](https://moment.github.io/luxon/)

**Comment by miam-miam100** [comment]
Fixed in commit 15bd6fb4c3f4b640d55605c22f71af3b93f033c8.
