### ISSUE TITLE
Github actions with eslint?

### ISSUE THREAD

**Issue by miam-miam100** [Diegovano/bomboclaat#37]
Should I do it so that eslint rules are followed when we push? This would only really make sense if we remove eslint config files from the gitignore.

**Comment by Diegovano** [comment]
I'd say only after the rewrite because for the moment the conventions are a bit all over the place.

I will move everything over to the standard JS convention when we're done with the rewrite, and at that point, I think it would be good to have it as a test!

**Comment by Diegovano** [comment]
Github action now runs npm test which checks for semistandard convention.
